modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/KnightMiner/Ceramics/issues/"
license="MIT"
[[mods]]
modId="ceramics"
version="${version}"
displayName="Ceramics"
displayURL="https://minecraft.curseforge.com/projects/ceramics"
# logoFile="examplemod.png"
credits="Much of the code for clay buckets is based off the Forge universal bucket"
authors="KnightMiner"
description='''
Mod adding additional early game and vanilla-like tools made of clay. Includes fluid transport, decoration, and ceramic tools.
'''
[[dependencies.ceramics]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ceramics]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramics]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"
