# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[27,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/KnightMiner/Ceramics/issues/"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="ceramics"
version="${file.jarVersion}"
displayName="Ceramics"
# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="" #optional
displayURL="https://minecraft.curseforge.com/projects/ceramics" #optional
# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Much of the code for clay buckets is based off the Forge universal bucket" #optional
authors="KnightMiner"
# The description text for the mod (multi line!) (#mandatory)
description='''
Mod adding additional early game and vanilla-like tools made of clay. Includes fluid transport, decoration, and ceramic tools.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ceramics]] 
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)" #mandatory
    ordering="AFTER"
    side="BOTH"
[[dependencies.inspirations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,]"
    ordering="NONE"
    side="BOTH"
